name: IaC Deployment

on: 
  push:
    branches: [ master ]
    paths: 'IaC/**'
  workflow_dispatch:

env:
    AzureResourceGroupName: 'oip'
    ResourceGroupLocation : 'northeurope'
    AppNamePrefix : 'oip'
    Environment: 'nonprod'
    AzSubscription: 'b861f44e-a700-4255-b9f2-c462bbda50ee'
    TenantID: '51575b39-28de-4120-94c6-af4c743f70f1'
    HubSiteUrl: 'https://onrocks.sharepoint.com/sites/RelationHubSite'
    
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout code
    - uses: actions/checkout@v2

    - name: Get Project Request List
      run: |
        Import-Module ./IaC/CreateList.psm1
        $ListId = New-RequestList -HubSiteUrl ${{env.HubSiteUrl}} -ClientID ${{secrets.CLIENTID}} -Certificate ${{secrets.CLIENTSECRET}} -TenantID ${{env.TenantID}}
        echo "::set-output name=List_Id::$ListId"
        Write-Host $ListId
      id: Get_Project_List
      shell: pwsh

    - name: Get Project Email List
      run: |
        Import-Module ./IaC/CreateList.psm1
        $MailListId = New-MailList -HubSiteUrl ${{env.HubSiteUrl}} -ClientID ${{secrets.CLIENTID}} -Certificate ${{secrets.CLIENTSECRET}} -TenantID ${{env.TenantID}}
        echo "::set-output name=MailList_Id::$MailListId"
        Write-Host $MailListId
      id: Get_Project_Mail_List
      shell: pwsh

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    # Deployment
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.36.0
        inlineScript: |
          az account set --subscription ${{ env.AzSubscription }}
          az deployment sub create --name azFunction --template-file ./IaC/main.bicep --location ${{ env.ResourceGroupLocation }} --parameters resourceGroupName=${{ env.AzureResourceGroupName }} resourceGroupLocation=${{ env.ResourceGroupLocation }} environment=${{ env.Environment }} appNamePrefix=${{ env.AppNamePrefix }} HubSite=${{env.HubSiteUrl}} RequestListId=${{steps.Get_Project_List.outputs.List_Id}} MailListId=${{steps.Get_Project_Mail_List.outputs.MailList_Id}}